source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GMUrlSigner_Example', :exclusive => true do
  pod "GMUrlSigner", :path => "../"
end

target 'GMUrlSigner_Tests', :exclusive => true do
  pod "GMUrlSigner", :path => "../"

  
end
